### ISSUE TITLE
Unintended blockquote on prgrams page

### ISSUE THREAD

**Issue by kewisch** [canonical/canonical-indico-themes#13]
On https://events.canonical.com/event/2/program it looks like the intro text is in blockquote. I suspect this is a design issue and not intended? Would be great to remove the blockquote bar.

**Comment by petesfrench** [comment]
Hi @kewisch, nothing in the style I created would have done this. Either this is the default behavior or has been done from the 'Management' section of Indico. We should see if this is set in 'Management', if not we can update the plugin manually.

**Comment by brittyazel** [comment]
I don't believe it is set in the management section. I just looked and can't find anything alluding to it.

**Comment by kewisch** [comment]
It looks like this is intended that way: https://github.com/indico/indico/blob/57acb4eac266feafac7c7be70e2d4f38851c12d6/indico/modules/events/tracks/templates/display.html#L18

I'd suggest we add a rule 

```
.quotation.tracks {
  margin: 0;
  border: 0;
  padding-left: 0;
}
```
