### ISSUE TITLE
Longer translations overflow on the registration page

### ISSUE THREAD

**Issue by Saviq** [canonical/canonical-indico-themes#14]
![image](https://user-images.githubusercontent.com/231077/189907199-3e4e45b7-67b9-4c62-8fd3-e785414f6b75.png)

**Comment by brittyazel** [comment]
Another member sent me a screenshot with the same issue 
![Ubuntu summit 2](https://user-images.githubusercontent.com/3747347/189954157-0d0c41fa-1c68-45c0-9ed1-60688659fb82.png)
