### ISSUE TITLE
White gap on header

### ISSUE THREAD

**Issue by brittyazel** [canonical/canonical-indico-themes#15]
![Ubuntu Summit website](https://user-images.githubusercontent.com/3747347/189954338-5ddbad33-1bfd-4eb1-9131-766b7b05a37c.png)

A user reported the above screenshot to me showing a large white gap in their header. I'm not sure if this is due to her using a Spanish version of the site or not.

**Comment by petesfrench** [comment]
@brittyazel I haven't been able to replicate this issue, but I am updating the banner today anyway so maybe that solves it.

**Comment by kewisch** [comment]
Let's assume this is taken care of, I haven't seen this either
