### ISSUE TITLE
Header bar unclickable due to overlapping image

### ISSUE THREAD

**Issue by kewisch** [canonical/canonical-indico-themes#17]
With the new banner, clicking on any icon in the header bar does not work, I suspect because the logo image overlaps it.  I like that the geometry is extending into the header (at least where there are no icons), but we should still make it possible to click the icons.

![image](https://user-images.githubusercontent.com/607198/191734425-1268eef0-23df-484e-8dbc-7941bd035c08.png)

**Comment by bogdans-canonical** [comment]
Hi @kewisch ! Is this issue fixed ? Thanks.

**Comment by kewisch** [comment]
Yes, tested this on stage, works great now!
