### ISSUE TITLE
Mobile/narrow view is missing the logo

### ISSUE THREAD

**Issue by kewisch** [canonical/canonical-indico-themes#20]
At under ~1250px the logo disappears. I feel there is still enough space to display it for a while longer, and I wonder if there is a way we could also display the logo in some way in a mobile width?

**Comment by kewisch** [comment]
Maybe something like this, but IANAD :-) 
![grafik](https://user-images.githubusercontent.com/607198/192749124-affd4c4c-3be5-4695-8053-64a69fc6eeef.png)

**Comment by petesfrench** [comment]
What do you think of this @spencerbygraves?

**Comment by spencerbygraves** [comment]
@petesfrench I think you can give it a try, but we should make sure the logo never interferes with the text. Thanks.

**Comment by kewisch** [comment]
No longer necessary, but we should take this into account for the next design.
