### ISSUE TITLE
Automatically populate a local "Canonical" group with staff members

### ISSUE THREAD

**Issue by kewisch** [canonical/canonical-indico-themes#23]
This is `canonical-indico-themes` and this request is not for a theme change, but on the other hand it is the only actual plugin we have, and this request is for plugin code.

I'd like a local group to be auto-populated with all Canonical staff members. It does not appear there is an automatic setting for this, so it would be a matter of doing something like this: https://talk.getindico.io/t/assign-group-automatically-for-edugain-identities-depending-in-idp/2741

In addition to the snippet there, we also need an offboarding mechanism, e.g. when an employee exits that group needs to be removed on login, and given indico session time is fairly long we'll also need to log out users in some way.

**Comment by kewisch** [comment]
Note also, the LDAP auth plugin apparently has a way to configure groups based on LDAP group membership, but I am suspecting we are using SAML.

**Comment by petesfrench** [comment]
Hey Phillip, I will look into to this and see how much work it would be. 

However, this is definitely outside the scope of the work that was agreed upon at the start of the project. So no guarantees it will get done soon.
