### ISSUE TITLE
Black font on black background

### ISSUE THREAD

**Issue by kewisch** [canonical/canonical-indico-themes#24]
There is a rule that forces --brand-black on all divs, headers, etc. This works fine, but there are some properties that have black backgrounds. The example I found is the location popup, but there are more. @petesfrench do we have a better way to set the default font color?

https://github.com/indico/indico/search?q=background-color%3A+%24black%3B

Expected:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/607198/195442829-1673b3b6-0b9d-4c34-969e-4c9bad625818.png">

Actual:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/607198/195442935-30f81897-b316-4207-b76c-4fe64095268d.png">

**Comment by kewisch** [comment]
Adding some more examples as I find them:

`.contrib-type` and `.contrib-track` from _conferences.scss gets overwritten to be black, which makes it blue/grey on black, instead of the default white(-ish) 
![image](https://user-images.githubusercontent.com/607198/195721319-16497a5c-50e7-4c57-a9aa-6bb7aab04a99.png)

**Comment by petesfrench** [comment]
We cant change any of the SCSS variables contained with the Indico project, but I can manually overwrite some of the default on the CSS/plugin side

**Comment by kewisch** [comment]
I just noticed this change overwrites qtips with a white background, such as here (content selected to make it visible)

<img width="415" alt="image" src="https://user-images.githubusercontent.com/607198/197059853-5333a6fa-de62-4aec-8c77-a8d7531a0240.png">

**Comment by kewisch** [comment]
Related (also visible in screenshot), the black text is overwriting the white text color for some of the timetable boxes.

**Comment by kewisch** [comment]
23b6aa55a78207082be0863ed9ef788ad301b612
