### ISSUE TITLE
Build custom banner for internal sprints

### ISSUE THREAD

**Issue by petesfrench** [canonical/canonical-indico-themes#32]
We have a request for  new banner for internal sprints. This will require a separate theme.
issue: https://github.com/canonical/web-squad/issues/6096

**Comment by spencerbygraves** [comment]
@petesfrench you can see the design [here](https://github.com/canonical/web-squad/issues/6096#issuecomment-1293469820). It's the first one with orange gradient. It should be ok to use the Canonical logo as it's for internal use only.

**Comment by petesfrench** [comment]
This might be covered by the work on [this pr](https://github.com/canonical/canonical-indico-themes/pull/33) I will reach out to Sarah to find out
